### PR TITLE
Create a listing tasks route

### PR DESCRIPTION
**Pull request by arturfsousa**
Hey @heynemann. This PR adds a new `/tasks` route to list all saved tasks on the api. I was thinking about pagination and filtering this route too, but I wanted to send this first as a start. What do you think?

### CODE REVIEW

**Comment by heynemann** [comment]
Very good PR. A couple improvements:

* Implement a `to_dict` method in the Task Model, similar to what is already existent in `Job` and `JobExecution` with the data you sent back in the JSON response. That way we have to manage data in one place only;
* Definitely implement pagination. We can fix the `page_size` (it can be a configuration), and pass the `page` as a querystring.

Good Job!

**Comment by arturfsousa** [comment]
Hi @heynemann, changes were done. I also added a `get_url` method that could be useful to centralize all `task_url` repetition in the code: 

https://github.com/heynemann/fastlane/pull/4/commits/9ea7d5fd619cf8a1f0cfdc722ae5353cc5c636ce#diff-82302cb418c8d2f8780430ab6f5766a9R42

I found 5 of them, so I thought that it would be nice to have it as a `Task` model method. What do you think about it?

If it's ok to you, I can go back and change all of them.

I also fixed the testing config to use `mongomock` instead of the local default `mongodb` instance:

https://github.com/heynemann/fastlane/pull/4/commits/2ce2fe015f8b9b6c4d6a888a719d2c48f5092845

This will avoid erasing previous local data when running tests.

**Comment by heynemann** [comment]
Brilliant! 👍 Please change all of the places to get_url.

Another change is that both in the to_dict and the list all tasks route, you are returning snake cased names (`last_modified`) and since it will be JSON we should return camel case (`lastModified`).

**Comment by heynemann** [comment]
thank you very much!!!

**Pull request merged**
